version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build Docker image
          command: docker build -t your-docker-username/your-image-name .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push your-docker-username/your-image-name
  test:
    executor: node/default
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Pull Docker image from Docker Hub
          command: docker pull your-docker-username/your-image-name
      - run:
          name: Run Docker container
          command: docker run -d -p 8080:8080 your-docker-username/your-image-name
workflows:
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
