version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t calvinjohnson747/my-node-app .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push calvinjohnson747/my-node-app
  deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Pull Docker image from Docker Hub
          command: docker pull calvinjohnson747/my-node-app
      - run:
          name: Run Docker container
          command: docker run -d -p 8080:8080 calvinjohnson747/my-node-app
workflows:
  build-test-and-deploy:
    jobs:
      - build
      - deploy
